baseURL: https://kvkvkv01.github.io/
languageCode: en-us
title: kvkvkv01
theme: nord

params:
  author: kvkvkv01
  description: "A student at 42rio"

menu:
  main:
    - name: Resume
      url: /resume/
      weight: 10
    - name: Works
      url: /works/
      weight: 20
